// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/rule_update.proto

package com.hzs.user_update_daemon.proto;

public final class RuleUpdateProto {
  private RuleUpdateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_proto_RuleUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_proto_RuleUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_proto_UserRangeRuleUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_proto_UserRangeRuleUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_proto_UserRuleUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_proto_UserRuleUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/java/rule_update.proto\022\026com.ex" +
      "ample.demo.proto\"F\n\nRuleUpdate\022\017\n\007rule_i" +
      "d\030\001 \001(\t\022\021\n\trule_name\030\002 \001(\t\022\024\n\014rule_versi" +
      "on\030\003 \001(\005\"y\n\023UserRangeRuleUpdate\022\017\n\007rule_" +
      "id\030\001 \001(\t\022\021\n\trule_name\030\002 \001(\t\022\024\n\014rule_vers" +
      "ion\030\003 \001(\005\022\023\n\013min_user_id\030\004 \001(\005\022\023\n\013max_us" +
      "er_id\030\005 \001(\005\"[\n\016UserRuleUpdate\022\017\n\007user_id" +
      "\030\001 \001(\005\022\017\n\007rule_id\030\002 \001(\t\022\021\n\trule_name\030\003 \001" +
      "(\t\022\024\n\014rule_version\030\004 \001(\005B\023B\017RuleUpdatePr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_proto_RuleUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_proto_RuleUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_proto_RuleUpdate_descriptor,
        new java.lang.String[] { "RuleId", "RuleName", "RuleVersion", });
    internal_static_com_example_demo_proto_UserRangeRuleUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_proto_UserRangeRuleUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_proto_UserRangeRuleUpdate_descriptor,
        new java.lang.String[] { "RuleId", "RuleName", "RuleVersion", "MinUserId", "MaxUserId", });
    internal_static_com_example_demo_proto_UserRuleUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_proto_UserRuleUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_proto_UserRuleUpdate_descriptor,
        new java.lang.String[] { "UserId", "RuleId", "RuleName", "RuleVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
