// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/rule_update.proto

package com.hzs.user_update_daemon.proto;

public interface UserRangeRuleUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.proto.UserRangeRuleUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rule_id = 1;</code>
   * @return The ruleId.
   */
  java.lang.String getRuleId();
  /**
   * <code>string rule_id = 1;</code>
   * @return The bytes for ruleId.
   */
  com.google.protobuf.ByteString
      getRuleIdBytes();

  /**
   * <code>string rule_name = 2;</code>
   * @return The ruleName.
   */
  java.lang.String getRuleName();
  /**
   * <code>string rule_name = 2;</code>
   * @return The bytes for ruleName.
   */
  com.google.protobuf.ByteString
      getRuleNameBytes();

  /**
   * <code>int32 rule_version = 3;</code>
   * @return The ruleVersion.
   */
  int getRuleVersion();

  /**
   * <code>int32 min_user_id = 4;</code>
   * @return The minUserId.
   */
  int getMinUserId();

  /**
   * <code>int32 max_user_id = 5;</code>
   * @return The maxUserId.
   */
  int getMaxUserId();
}
