// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

package com.hzs.SegServe.proto;

public interface CampaignOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzs.SegServe.proto.Campaign)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Add this line
   * </pre>
   *
   * <code>optional string campaign_id = 1;</code>
   * @return Whether the campaignId field is set.
   */
  boolean hasCampaignId();
  /**
   * <pre>
   * Add this line
   * </pre>
   *
   * <code>optional string campaign_id = 1;</code>
   * @return The campaignId.
   */
  java.lang.String getCampaignId();
  /**
   * <pre>
   * Add this line
   * </pre>
   *
   * <code>optional string campaign_id = 1;</code>
   * @return The bytes for campaignId.
   */
  com.google.protobuf.ByteString
      getCampaignIdBytes();

  /**
   * <code>optional string rule_id = 2;</code>
   * @return Whether the ruleId field is set.
   */
  boolean hasRuleId();
  /**
   * <code>optional string rule_id = 2;</code>
   * @return The ruleId.
   */
  java.lang.String getRuleId();
  /**
   * <code>optional string rule_id = 2;</code>
   * @return The bytes for ruleId.
   */
  com.google.protobuf.ByteString
      getRuleIdBytes();

  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 3;</code>
   * @return Whether the schedule field is set.
   */
  boolean hasSchedule();
  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 3;</code>
   * @return The schedule.
   */
  com.hzs.SegServe.proto.Schedule getSchedule();
  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 3;</code>
   */
  com.hzs.SegServe.proto.ScheduleOrBuilder getScheduleOrBuilder();

  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 4;</code>
   */
  java.util.List<com.hzs.SegServe.proto.Target> 
      getTargetList();
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 4;</code>
   */
  com.hzs.SegServe.proto.Target getTarget(int index);
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 4;</code>
   */
  int getTargetCount();
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 4;</code>
   */
  java.util.List<? extends com.hzs.SegServe.proto.TargetOrBuilder> 
      getTargetOrBuilderList();
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 4;</code>
   */
  com.hzs.SegServe.proto.TargetOrBuilder getTargetOrBuilder(
      int index);
}
