package com.hzs.SegServe.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

public interface HomePageShelfTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HomePageShelfTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string shelf_id = 1;</code>
   * @return Whether the shelfId field is set.
   */
  boolean hasShelfId();
  /**
   * <code>optional string shelf_id = 1;</code>
   * @return The shelfId.
   */
  java.lang.String getShelfId();
  /**
   * <code>optional string shelf_id = 1;</code>
   * @return The bytes for shelfId.
   */
  com.google.protobuf.ByteString
      getShelfIdBytes();
}
