package com.hzs.SegServe.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

public interface LoginActivityRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginActivityRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string last_login_date = 1;</code>
   * @return Whether the lastLoginDate field is set.
   */
  boolean hasLastLoginDate();
  /**
   * <code>optional string last_login_date = 1;</code>
   * @return The lastLoginDate.
   */
  java.lang.String getLastLoginDate();
  /**
   * <code>optional string last_login_date = 1;</code>
   * @return The bytes for lastLoginDate.
   */
  com.google.protobuf.ByteString
      getLastLoginDateBytes();
}
