// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

package com.hzs.SegServe.proto;

/**
 * <pre>
 * Represents a Rule used in segmentation
 * </pre>
 *
 * Protobuf type {@code com.hzs.SegServe.proto.Rule}
 */
public final class Rule extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hzs.SegServe.proto.Rule)
    RuleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Rule.newBuilder() to construct.
  private Rule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Rule() {
    ruleId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Rule();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Rule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Rule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hzs.SegServe.proto.Rule.class, com.hzs.SegServe.proto.Rule.Builder.class);
  }

  private int bitField0_;
  private int ruleCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object rule_;
  public enum RuleCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PLAY_ACTIVITY_RULE(2),
    SUBSCRIPTION_RULE(3),
    LOGIN_ACTIVITY_RULE(4),
    RULE_NOT_SET(0);
    private final int value;
    private RuleCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RuleCase valueOf(int value) {
      return forNumber(value);
    }

    public static RuleCase forNumber(int value) {
      switch (value) {
        case 2: return PLAY_ACTIVITY_RULE;
        case 3: return SUBSCRIPTION_RULE;
        case 4: return LOGIN_ACTIVITY_RULE;
        case 0: return RULE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RuleCase
  getRuleCase() {
    return RuleCase.forNumber(
        ruleCase_);
  }

  public static final int RULE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ruleId_ = "";
  /**
   * <code>optional string rule_id = 1;</code>
   * @return Whether the ruleId field is set.
   */
  @java.lang.Override
  public boolean hasRuleId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string rule_id = 1;</code>
   * @return The ruleId.
   */
  @java.lang.Override
  public java.lang.String getRuleId() {
    java.lang.Object ref = ruleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ruleId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string rule_id = 1;</code>
   * @return The bytes for ruleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuleIdBytes() {
    java.lang.Object ref = ruleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ruleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAY_ACTIVITY_RULE_FIELD_NUMBER = 2;
  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   * @return Whether the playActivityRule field is set.
   */
  @java.lang.Override
  public boolean hasPlayActivityRule() {
    return ruleCase_ == 2;
  }
  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   * @return The playActivityRule.
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.PlayActivityRule getPlayActivityRule() {
    if (ruleCase_ == 2) {
       return (com.hzs.SegServe.proto.PlayActivityRule) rule_;
    }
    return com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
  }
  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.PlayActivityRuleOrBuilder getPlayActivityRuleOrBuilder() {
    if (ruleCase_ == 2) {
       return (com.hzs.SegServe.proto.PlayActivityRule) rule_;
    }
    return com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
  }

  public static final int SUBSCRIPTION_RULE_FIELD_NUMBER = 3;
  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   * @return Whether the subscriptionRule field is set.
   */
  @java.lang.Override
  public boolean hasSubscriptionRule() {
    return ruleCase_ == 3;
  }
  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   * @return The subscriptionRule.
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.SubscriptionRule getSubscriptionRule() {
    if (ruleCase_ == 3) {
       return (com.hzs.SegServe.proto.SubscriptionRule) rule_;
    }
    return com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
  }
  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.SubscriptionRuleOrBuilder getSubscriptionRuleOrBuilder() {
    if (ruleCase_ == 3) {
       return (com.hzs.SegServe.proto.SubscriptionRule) rule_;
    }
    return com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
  }

  public static final int LOGIN_ACTIVITY_RULE_FIELD_NUMBER = 4;
  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   * @return Whether the loginActivityRule field is set.
   */
  @java.lang.Override
  public boolean hasLoginActivityRule() {
    return ruleCase_ == 4;
  }
  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   * @return The loginActivityRule.
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.LoginActivityRule getLoginActivityRule() {
    if (ruleCase_ == 4) {
       return (com.hzs.SegServe.proto.LoginActivityRule) rule_;
    }
    return com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
  }
  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.LoginActivityRuleOrBuilder getLoginActivityRuleOrBuilder() {
    if (ruleCase_ == 4) {
       return (com.hzs.SegServe.proto.LoginActivityRule) rule_;
    }
    return com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ruleId_);
    }
    if (ruleCase_ == 2) {
      output.writeMessage(2, (com.hzs.SegServe.proto.PlayActivityRule) rule_);
    }
    if (ruleCase_ == 3) {
      output.writeMessage(3, (com.hzs.SegServe.proto.SubscriptionRule) rule_);
    }
    if (ruleCase_ == 4) {
      output.writeMessage(4, (com.hzs.SegServe.proto.LoginActivityRule) rule_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ruleId_);
    }
    if (ruleCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.hzs.SegServe.proto.PlayActivityRule) rule_);
    }
    if (ruleCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.hzs.SegServe.proto.SubscriptionRule) rule_);
    }
    if (ruleCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.hzs.SegServe.proto.LoginActivityRule) rule_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hzs.SegServe.proto.Rule)) {
      return super.equals(obj);
    }
    com.hzs.SegServe.proto.Rule other = (com.hzs.SegServe.proto.Rule) obj;

    if (hasRuleId() != other.hasRuleId()) return false;
    if (hasRuleId()) {
      if (!getRuleId()
          .equals(other.getRuleId())) return false;
    }
    if (!getRuleCase().equals(other.getRuleCase())) return false;
    switch (ruleCase_) {
      case 2:
        if (!getPlayActivityRule()
            .equals(other.getPlayActivityRule())) return false;
        break;
      case 3:
        if (!getSubscriptionRule()
            .equals(other.getSubscriptionRule())) return false;
        break;
      case 4:
        if (!getLoginActivityRule()
            .equals(other.getLoginActivityRule())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRuleId()) {
      hash = (37 * hash) + RULE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRuleId().hashCode();
    }
    switch (ruleCase_) {
      case 2:
        hash = (37 * hash) + PLAY_ACTIVITY_RULE_FIELD_NUMBER;
        hash = (53 * hash) + getPlayActivityRule().hashCode();
        break;
      case 3:
        hash = (37 * hash) + SUBSCRIPTION_RULE_FIELD_NUMBER;
        hash = (53 * hash) + getSubscriptionRule().hashCode();
        break;
      case 4:
        hash = (37 * hash) + LOGIN_ACTIVITY_RULE_FIELD_NUMBER;
        hash = (53 * hash) + getLoginActivityRule().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hzs.SegServe.proto.Rule parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hzs.SegServe.proto.Rule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hzs.SegServe.proto.Rule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.SegServe.proto.Rule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hzs.SegServe.proto.Rule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a Rule used in segmentation
   * </pre>
   *
   * Protobuf type {@code com.hzs.SegServe.proto.Rule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hzs.SegServe.proto.Rule)
      com.hzs.SegServe.proto.RuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Rule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Rule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzs.SegServe.proto.Rule.class, com.hzs.SegServe.proto.Rule.Builder.class);
    }

    // Construct using com.hzs.SegServe.proto.Rule.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ruleId_ = "";
      if (playActivityRuleBuilder_ != null) {
        playActivityRuleBuilder_.clear();
      }
      if (subscriptionRuleBuilder_ != null) {
        subscriptionRuleBuilder_.clear();
      }
      if (loginActivityRuleBuilder_ != null) {
        loginActivityRuleBuilder_.clear();
      }
      ruleCase_ = 0;
      rule_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Rule_descriptor;
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Rule getDefaultInstanceForType() {
      return com.hzs.SegServe.proto.Rule.getDefaultInstance();
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Rule build() {
      com.hzs.SegServe.proto.Rule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Rule buildPartial() {
      com.hzs.SegServe.proto.Rule result = new com.hzs.SegServe.proto.Rule(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hzs.SegServe.proto.Rule result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ruleId_ = ruleId_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.hzs.SegServe.proto.Rule result) {
      result.ruleCase_ = ruleCase_;
      result.rule_ = this.rule_;
      if (ruleCase_ == 2 &&
          playActivityRuleBuilder_ != null) {
        result.rule_ = playActivityRuleBuilder_.build();
      }
      if (ruleCase_ == 3 &&
          subscriptionRuleBuilder_ != null) {
        result.rule_ = subscriptionRuleBuilder_.build();
      }
      if (ruleCase_ == 4 &&
          loginActivityRuleBuilder_ != null) {
        result.rule_ = loginActivityRuleBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hzs.SegServe.proto.Rule) {
        return mergeFrom((com.hzs.SegServe.proto.Rule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hzs.SegServe.proto.Rule other) {
      if (other == com.hzs.SegServe.proto.Rule.getDefaultInstance()) return this;
      if (other.hasRuleId()) {
        ruleId_ = other.ruleId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      switch (other.getRuleCase()) {
        case PLAY_ACTIVITY_RULE: {
          mergePlayActivityRule(other.getPlayActivityRule());
          break;
        }
        case SUBSCRIPTION_RULE: {
          mergeSubscriptionRule(other.getSubscriptionRule());
          break;
        }
        case LOGIN_ACTIVITY_RULE: {
          mergeLoginActivityRule(other.getLoginActivityRule());
          break;
        }
        case RULE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ruleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPlayActivityRuleFieldBuilder().getBuilder(),
                  extensionRegistry);
              ruleCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubscriptionRuleFieldBuilder().getBuilder(),
                  extensionRegistry);
              ruleCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getLoginActivityRuleFieldBuilder().getBuilder(),
                  extensionRegistry);
              ruleCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int ruleCase_ = 0;
    private java.lang.Object rule_;
    public RuleCase
        getRuleCase() {
      return RuleCase.forNumber(
          ruleCase_);
    }

    public Builder clearRule() {
      ruleCase_ = 0;
      rule_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object ruleId_ = "";
    /**
     * <code>optional string rule_id = 1;</code>
     * @return Whether the ruleId field is set.
     */
    public boolean hasRuleId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string rule_id = 1;</code>
     * @return The ruleId.
     */
    public java.lang.String getRuleId() {
      java.lang.Object ref = ruleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string rule_id = 1;</code>
     * @return The bytes for ruleId.
     */
    public com.google.protobuf.ByteString
        getRuleIdBytes() {
      java.lang.Object ref = ruleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string rule_id = 1;</code>
     * @param value The ruleId to set.
     * @return This builder for chaining.
     */
    public Builder setRuleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ruleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string rule_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuleId() {
      ruleId_ = getDefaultInstance().getRuleId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string rule_id = 1;</code>
     * @param value The bytes for ruleId to set.
     * @return This builder for chaining.
     */
    public Builder setRuleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ruleId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.PlayActivityRule, com.hzs.SegServe.proto.PlayActivityRule.Builder, com.hzs.SegServe.proto.PlayActivityRuleOrBuilder> playActivityRuleBuilder_;
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     * @return Whether the playActivityRule field is set.
     */
    @java.lang.Override
    public boolean hasPlayActivityRule() {
      return ruleCase_ == 2;
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     * @return The playActivityRule.
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.PlayActivityRule getPlayActivityRule() {
      if (playActivityRuleBuilder_ == null) {
        if (ruleCase_ == 2) {
          return (com.hzs.SegServe.proto.PlayActivityRule) rule_;
        }
        return com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
      } else {
        if (ruleCase_ == 2) {
          return playActivityRuleBuilder_.getMessage();
        }
        return com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    public Builder setPlayActivityRule(com.hzs.SegServe.proto.PlayActivityRule value) {
      if (playActivityRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rule_ = value;
        onChanged();
      } else {
        playActivityRuleBuilder_.setMessage(value);
      }
      ruleCase_ = 2;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    public Builder setPlayActivityRule(
        com.hzs.SegServe.proto.PlayActivityRule.Builder builderForValue) {
      if (playActivityRuleBuilder_ == null) {
        rule_ = builderForValue.build();
        onChanged();
      } else {
        playActivityRuleBuilder_.setMessage(builderForValue.build());
      }
      ruleCase_ = 2;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    public Builder mergePlayActivityRule(com.hzs.SegServe.proto.PlayActivityRule value) {
      if (playActivityRuleBuilder_ == null) {
        if (ruleCase_ == 2 &&
            rule_ != com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance()) {
          rule_ = com.hzs.SegServe.proto.PlayActivityRule.newBuilder((com.hzs.SegServe.proto.PlayActivityRule) rule_)
              .mergeFrom(value).buildPartial();
        } else {
          rule_ = value;
        }
        onChanged();
      } else {
        if (ruleCase_ == 2) {
          playActivityRuleBuilder_.mergeFrom(value);
        } else {
          playActivityRuleBuilder_.setMessage(value);
        }
      }
      ruleCase_ = 2;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    public Builder clearPlayActivityRule() {
      if (playActivityRuleBuilder_ == null) {
        if (ruleCase_ == 2) {
          ruleCase_ = 0;
          rule_ = null;
          onChanged();
        }
      } else {
        if (ruleCase_ == 2) {
          ruleCase_ = 0;
          rule_ = null;
        }
        playActivityRuleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    public com.hzs.SegServe.proto.PlayActivityRule.Builder getPlayActivityRuleBuilder() {
      return getPlayActivityRuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.PlayActivityRuleOrBuilder getPlayActivityRuleOrBuilder() {
      if ((ruleCase_ == 2) && (playActivityRuleBuilder_ != null)) {
        return playActivityRuleBuilder_.getMessageOrBuilder();
      } else {
        if (ruleCase_ == 2) {
          return (com.hzs.SegServe.proto.PlayActivityRule) rule_;
        }
        return com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.PlayActivityRule, com.hzs.SegServe.proto.PlayActivityRule.Builder, com.hzs.SegServe.proto.PlayActivityRuleOrBuilder> 
        getPlayActivityRuleFieldBuilder() {
      if (playActivityRuleBuilder_ == null) {
        if (!(ruleCase_ == 2)) {
          rule_ = com.hzs.SegServe.proto.PlayActivityRule.getDefaultInstance();
        }
        playActivityRuleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hzs.SegServe.proto.PlayActivityRule, com.hzs.SegServe.proto.PlayActivityRule.Builder, com.hzs.SegServe.proto.PlayActivityRuleOrBuilder>(
                (com.hzs.SegServe.proto.PlayActivityRule) rule_,
                getParentForChildren(),
                isClean());
        rule_ = null;
      }
      ruleCase_ = 2;
      onChanged();
      return playActivityRuleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.SubscriptionRule, com.hzs.SegServe.proto.SubscriptionRule.Builder, com.hzs.SegServe.proto.SubscriptionRuleOrBuilder> subscriptionRuleBuilder_;
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     * @return Whether the subscriptionRule field is set.
     */
    @java.lang.Override
    public boolean hasSubscriptionRule() {
      return ruleCase_ == 3;
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     * @return The subscriptionRule.
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.SubscriptionRule getSubscriptionRule() {
      if (subscriptionRuleBuilder_ == null) {
        if (ruleCase_ == 3) {
          return (com.hzs.SegServe.proto.SubscriptionRule) rule_;
        }
        return com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
      } else {
        if (ruleCase_ == 3) {
          return subscriptionRuleBuilder_.getMessage();
        }
        return com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    public Builder setSubscriptionRule(com.hzs.SegServe.proto.SubscriptionRule value) {
      if (subscriptionRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rule_ = value;
        onChanged();
      } else {
        subscriptionRuleBuilder_.setMessage(value);
      }
      ruleCase_ = 3;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    public Builder setSubscriptionRule(
        com.hzs.SegServe.proto.SubscriptionRule.Builder builderForValue) {
      if (subscriptionRuleBuilder_ == null) {
        rule_ = builderForValue.build();
        onChanged();
      } else {
        subscriptionRuleBuilder_.setMessage(builderForValue.build());
      }
      ruleCase_ = 3;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    public Builder mergeSubscriptionRule(com.hzs.SegServe.proto.SubscriptionRule value) {
      if (subscriptionRuleBuilder_ == null) {
        if (ruleCase_ == 3 &&
            rule_ != com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance()) {
          rule_ = com.hzs.SegServe.proto.SubscriptionRule.newBuilder((com.hzs.SegServe.proto.SubscriptionRule) rule_)
              .mergeFrom(value).buildPartial();
        } else {
          rule_ = value;
        }
        onChanged();
      } else {
        if (ruleCase_ == 3) {
          subscriptionRuleBuilder_.mergeFrom(value);
        } else {
          subscriptionRuleBuilder_.setMessage(value);
        }
      }
      ruleCase_ = 3;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    public Builder clearSubscriptionRule() {
      if (subscriptionRuleBuilder_ == null) {
        if (ruleCase_ == 3) {
          ruleCase_ = 0;
          rule_ = null;
          onChanged();
        }
      } else {
        if (ruleCase_ == 3) {
          ruleCase_ = 0;
          rule_ = null;
        }
        subscriptionRuleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    public com.hzs.SegServe.proto.SubscriptionRule.Builder getSubscriptionRuleBuilder() {
      return getSubscriptionRuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.SubscriptionRuleOrBuilder getSubscriptionRuleOrBuilder() {
      if ((ruleCase_ == 3) && (subscriptionRuleBuilder_ != null)) {
        return subscriptionRuleBuilder_.getMessageOrBuilder();
      } else {
        if (ruleCase_ == 3) {
          return (com.hzs.SegServe.proto.SubscriptionRule) rule_;
        }
        return com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.SubscriptionRule, com.hzs.SegServe.proto.SubscriptionRule.Builder, com.hzs.SegServe.proto.SubscriptionRuleOrBuilder> 
        getSubscriptionRuleFieldBuilder() {
      if (subscriptionRuleBuilder_ == null) {
        if (!(ruleCase_ == 3)) {
          rule_ = com.hzs.SegServe.proto.SubscriptionRule.getDefaultInstance();
        }
        subscriptionRuleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hzs.SegServe.proto.SubscriptionRule, com.hzs.SegServe.proto.SubscriptionRule.Builder, com.hzs.SegServe.proto.SubscriptionRuleOrBuilder>(
                (com.hzs.SegServe.proto.SubscriptionRule) rule_,
                getParentForChildren(),
                isClean());
        rule_ = null;
      }
      ruleCase_ = 3;
      onChanged();
      return subscriptionRuleBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.LoginActivityRule, com.hzs.SegServe.proto.LoginActivityRule.Builder, com.hzs.SegServe.proto.LoginActivityRuleOrBuilder> loginActivityRuleBuilder_;
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     * @return Whether the loginActivityRule field is set.
     */
    @java.lang.Override
    public boolean hasLoginActivityRule() {
      return ruleCase_ == 4;
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     * @return The loginActivityRule.
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.LoginActivityRule getLoginActivityRule() {
      if (loginActivityRuleBuilder_ == null) {
        if (ruleCase_ == 4) {
          return (com.hzs.SegServe.proto.LoginActivityRule) rule_;
        }
        return com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
      } else {
        if (ruleCase_ == 4) {
          return loginActivityRuleBuilder_.getMessage();
        }
        return com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    public Builder setLoginActivityRule(com.hzs.SegServe.proto.LoginActivityRule value) {
      if (loginActivityRuleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rule_ = value;
        onChanged();
      } else {
        loginActivityRuleBuilder_.setMessage(value);
      }
      ruleCase_ = 4;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    public Builder setLoginActivityRule(
        com.hzs.SegServe.proto.LoginActivityRule.Builder builderForValue) {
      if (loginActivityRuleBuilder_ == null) {
        rule_ = builderForValue.build();
        onChanged();
      } else {
        loginActivityRuleBuilder_.setMessage(builderForValue.build());
      }
      ruleCase_ = 4;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    public Builder mergeLoginActivityRule(com.hzs.SegServe.proto.LoginActivityRule value) {
      if (loginActivityRuleBuilder_ == null) {
        if (ruleCase_ == 4 &&
            rule_ != com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance()) {
          rule_ = com.hzs.SegServe.proto.LoginActivityRule.newBuilder((com.hzs.SegServe.proto.LoginActivityRule) rule_)
              .mergeFrom(value).buildPartial();
        } else {
          rule_ = value;
        }
        onChanged();
      } else {
        if (ruleCase_ == 4) {
          loginActivityRuleBuilder_.mergeFrom(value);
        } else {
          loginActivityRuleBuilder_.setMessage(value);
        }
      }
      ruleCase_ = 4;
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    public Builder clearLoginActivityRule() {
      if (loginActivityRuleBuilder_ == null) {
        if (ruleCase_ == 4) {
          ruleCase_ = 0;
          rule_ = null;
          onChanged();
        }
      } else {
        if (ruleCase_ == 4) {
          ruleCase_ = 0;
          rule_ = null;
        }
        loginActivityRuleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    public com.hzs.SegServe.proto.LoginActivityRule.Builder getLoginActivityRuleBuilder() {
      return getLoginActivityRuleFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    @java.lang.Override
    public com.hzs.SegServe.proto.LoginActivityRuleOrBuilder getLoginActivityRuleOrBuilder() {
      if ((ruleCase_ == 4) && (loginActivityRuleBuilder_ != null)) {
        return loginActivityRuleBuilder_.getMessageOrBuilder();
      } else {
        if (ruleCase_ == 4) {
          return (com.hzs.SegServe.proto.LoginActivityRule) rule_;
        }
        return com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
      }
    }
    /**
     * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.LoginActivityRule, com.hzs.SegServe.proto.LoginActivityRule.Builder, com.hzs.SegServe.proto.LoginActivityRuleOrBuilder> 
        getLoginActivityRuleFieldBuilder() {
      if (loginActivityRuleBuilder_ == null) {
        if (!(ruleCase_ == 4)) {
          rule_ = com.hzs.SegServe.proto.LoginActivityRule.getDefaultInstance();
        }
        loginActivityRuleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hzs.SegServe.proto.LoginActivityRule, com.hzs.SegServe.proto.LoginActivityRule.Builder, com.hzs.SegServe.proto.LoginActivityRuleOrBuilder>(
                (com.hzs.SegServe.proto.LoginActivityRule) rule_,
                getParentForChildren(),
                isClean());
        rule_ = null;
      }
      ruleCase_ = 4;
      onChanged();
      return loginActivityRuleBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hzs.SegServe.proto.Rule)
  }

  // @@protoc_insertion_point(class_scope:com.hzs.SegServe.proto.Rule)
  private static final com.hzs.SegServe.proto.Rule DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hzs.SegServe.proto.Rule();
  }

  public static com.hzs.SegServe.proto.Rule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rule>
      PARSER = new com.google.protobuf.AbstractParser<Rule>() {
    @java.lang.Override
    public Rule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Rule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hzs.SegServe.proto.Rule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

