// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

package com.hzs.SegServe.proto;

public interface RuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzs.SegServe.proto.Rule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string rule_id = 1;</code>
   * @return Whether the ruleId field is set.
   */
  boolean hasRuleId();
  /**
   * <code>optional string rule_id = 1;</code>
   * @return The ruleId.
   */
  java.lang.String getRuleId();
  /**
   * <code>optional string rule_id = 1;</code>
   * @return The bytes for ruleId.
   */
  com.google.protobuf.ByteString
      getRuleIdBytes();

  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   * @return Whether the playActivityRule field is set.
   */
  boolean hasPlayActivityRule();
  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   * @return The playActivityRule.
   */
  com.hzs.SegServe.proto.PlayActivityRule getPlayActivityRule();
  /**
   * <code>.com.hzs.SegServe.proto.PlayActivityRule play_activity_rule = 2;</code>
   */
  com.hzs.SegServe.proto.PlayActivityRuleOrBuilder getPlayActivityRuleOrBuilder();

  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   * @return Whether the subscriptionRule field is set.
   */
  boolean hasSubscriptionRule();
  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   * @return The subscriptionRule.
   */
  com.hzs.SegServe.proto.SubscriptionRule getSubscriptionRule();
  /**
   * <code>.com.hzs.SegServe.proto.SubscriptionRule subscription_rule = 3;</code>
   */
  com.hzs.SegServe.proto.SubscriptionRuleOrBuilder getSubscriptionRuleOrBuilder();

  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   * @return Whether the loginActivityRule field is set.
   */
  boolean hasLoginActivityRule();
  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   * @return The loginActivityRule.
   */
  com.hzs.SegServe.proto.LoginActivityRule getLoginActivityRule();
  /**
   * <code>.com.hzs.SegServe.proto.LoginActivityRule login_activity_rule = 4;</code>
   */
  com.hzs.SegServe.proto.LoginActivityRuleOrBuilder getLoginActivityRuleOrBuilder();

  com.hzs.SegServe.proto.Rule.RuleCase getRuleCase();
}
