package com.hzs.SegServe.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

public interface TargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Target)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HomePageShelfTarget home_page = 1;</code>
   * @return Whether the homePage field is set.
   */
  boolean hasHomePage();
  /**
   * <code>.HomePageShelfTarget home_page = 1;</code>
   * @return The homePage.
   */
  HomePageShelfTarget getHomePage();
  /**
   * <code>.HomePageShelfTarget home_page = 1;</code>
   */
  HomePageShelfTargetOrBuilder getHomePageOrBuilder();

  /**
   * <code>.PostPlayShelfTarget post_play = 2;</code>
   * @return Whether the postPlay field is set.
   */
  boolean hasPostPlay();
  /**
   * <code>.PostPlayShelfTarget post_play = 2;</code>
   * @return The postPlay.
   */
  PostPlayShelfTarget getPostPlay();
  /**
   * <code>.PostPlayShelfTarget post_play = 2;</code>
   */
  PostPlayShelfTargetOrBuilder getPostPlayOrBuilder();

  /**
   * <code>.NotificationTarget notification = 3;</code>
   * @return Whether the notification field is set.
   */
  boolean hasNotification();
  /**
   * <code>.NotificationTarget notification = 3;</code>
   * @return The notification.
   */
  NotificationTarget getNotification();
  /**
   * <code>.NotificationTarget notification = 3;</code>
   */
  NotificationTargetOrBuilder getNotificationOrBuilder();

  Target.RuleCase getRuleCase();
}
