// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

package com.hzs.SegServe.proto;

/**
 * <pre>
 * Represents a Campaign with segmentation rules and targets
 * </pre>
 *
 * Protobuf type {@code com.hzs.SegServe.proto.Campaign}
 */
public final class Campaign extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hzs.SegServe.proto.Campaign)
    CampaignOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Campaign.newBuilder() to construct.
  private Campaign(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Campaign() {
    campaignId_ = "";
    campaignName_ = "";
    ruleId_ = "";
    target_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Campaign();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Campaign_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Campaign_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hzs.SegServe.proto.Campaign.class, com.hzs.SegServe.proto.Campaign.Builder.class);
  }

  private int bitField0_;
  public static final int CAMPAIGN_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object campaignId_ = "";
  /**
   * <code>optional string campaign_id = 1;</code>
   * @return Whether the campaignId field is set.
   */
  @java.lang.Override
  public boolean hasCampaignId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string campaign_id = 1;</code>
   * @return The campaignId.
   */
  @java.lang.Override
  public java.lang.String getCampaignId() {
    java.lang.Object ref = campaignId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      campaignId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string campaign_id = 1;</code>
   * @return The bytes for campaignId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCampaignIdBytes() {
    java.lang.Object ref = campaignId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      campaignId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMPAIGN_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object campaignName_ = "";
  /**
   * <code>optional string campaign_name = 2;</code>
   * @return Whether the campaignName field is set.
   */
  @java.lang.Override
  public boolean hasCampaignName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string campaign_name = 2;</code>
   * @return The campaignName.
   */
  @java.lang.Override
  public java.lang.String getCampaignName() {
    java.lang.Object ref = campaignName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      campaignName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string campaign_name = 2;</code>
   * @return The bytes for campaignName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCampaignNameBytes() {
    java.lang.Object ref = campaignName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      campaignName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RULE_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ruleId_ = "";
  /**
   * <code>optional string rule_id = 3;</code>
   * @return Whether the ruleId field is set.
   */
  @java.lang.Override
  public boolean hasRuleId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string rule_id = 3;</code>
   * @return The ruleId.
   */
  @java.lang.Override
  public java.lang.String getRuleId() {
    java.lang.Object ref = ruleId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ruleId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string rule_id = 3;</code>
   * @return The bytes for ruleId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuleIdBytes() {
    java.lang.Object ref = ruleId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ruleId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEDULE_FIELD_NUMBER = 4;
  private com.hzs.SegServe.proto.Schedule schedule_;
  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
   * @return Whether the schedule field is set.
   */
  @java.lang.Override
  public boolean hasSchedule() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
   * @return The schedule.
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.Schedule getSchedule() {
    return schedule_ == null ? com.hzs.SegServe.proto.Schedule.getDefaultInstance() : schedule_;
  }
  /**
   * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.ScheduleOrBuilder getScheduleOrBuilder() {
    return schedule_ == null ? com.hzs.SegServe.proto.Schedule.getDefaultInstance() : schedule_;
  }

  public static final int TARGET_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.hzs.SegServe.proto.Target> target_;
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.hzs.SegServe.proto.Target> getTargetList() {
    return target_;
  }
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.hzs.SegServe.proto.TargetOrBuilder> 
      getTargetOrBuilderList() {
    return target_;
  }
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
   */
  @java.lang.Override
  public int getTargetCount() {
    return target_.size();
  }
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.Target getTarget(int index) {
    return target_.get(index);
  }
  /**
   * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
   */
  @java.lang.Override
  public com.hzs.SegServe.proto.TargetOrBuilder getTargetOrBuilder(
      int index) {
    return target_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, campaignId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, campaignName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ruleId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getSchedule());
    }
    for (int i = 0; i < target_.size(); i++) {
      output.writeMessage(5, target_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, campaignId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, campaignName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ruleId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSchedule());
    }
    for (int i = 0; i < target_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, target_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hzs.SegServe.proto.Campaign)) {
      return super.equals(obj);
    }
    com.hzs.SegServe.proto.Campaign other = (com.hzs.SegServe.proto.Campaign) obj;

    if (hasCampaignId() != other.hasCampaignId()) return false;
    if (hasCampaignId()) {
      if (!getCampaignId()
          .equals(other.getCampaignId())) return false;
    }
    if (hasCampaignName() != other.hasCampaignName()) return false;
    if (hasCampaignName()) {
      if (!getCampaignName()
          .equals(other.getCampaignName())) return false;
    }
    if (hasRuleId() != other.hasRuleId()) return false;
    if (hasRuleId()) {
      if (!getRuleId()
          .equals(other.getRuleId())) return false;
    }
    if (hasSchedule() != other.hasSchedule()) return false;
    if (hasSchedule()) {
      if (!getSchedule()
          .equals(other.getSchedule())) return false;
    }
    if (!getTargetList()
        .equals(other.getTargetList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCampaignId()) {
      hash = (37 * hash) + CAMPAIGN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCampaignId().hashCode();
    }
    if (hasCampaignName()) {
      hash = (37 * hash) + CAMPAIGN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getCampaignName().hashCode();
    }
    if (hasRuleId()) {
      hash = (37 * hash) + RULE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRuleId().hashCode();
    }
    if (hasSchedule()) {
      hash = (37 * hash) + SCHEDULE_FIELD_NUMBER;
      hash = (53 * hash) + getSchedule().hashCode();
    }
    if (getTargetCount() > 0) {
      hash = (37 * hash) + TARGET_FIELD_NUMBER;
      hash = (53 * hash) + getTargetList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hzs.SegServe.proto.Campaign parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hzs.SegServe.proto.Campaign parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hzs.SegServe.proto.Campaign parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.SegServe.proto.Campaign parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hzs.SegServe.proto.Campaign prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a Campaign with segmentation rules and targets
   * </pre>
   *
   * Protobuf type {@code com.hzs.SegServe.proto.Campaign}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hzs.SegServe.proto.Campaign)
      com.hzs.SegServe.proto.CampaignOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Campaign_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Campaign_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzs.SegServe.proto.Campaign.class, com.hzs.SegServe.proto.Campaign.Builder.class);
    }

    // Construct using com.hzs.SegServe.proto.Campaign.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getScheduleFieldBuilder();
        getTargetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      campaignId_ = "";
      campaignName_ = "";
      ruleId_ = "";
      schedule_ = null;
      if (scheduleBuilder_ != null) {
        scheduleBuilder_.dispose();
        scheduleBuilder_ = null;
      }
      if (targetBuilder_ == null) {
        target_ = java.util.Collections.emptyList();
      } else {
        target_ = null;
        targetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hzs.SegServe.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_Campaign_descriptor;
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Campaign getDefaultInstanceForType() {
      return com.hzs.SegServe.proto.Campaign.getDefaultInstance();
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Campaign build() {
      com.hzs.SegServe.proto.Campaign result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hzs.SegServe.proto.Campaign buildPartial() {
      com.hzs.SegServe.proto.Campaign result = new com.hzs.SegServe.proto.Campaign(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.hzs.SegServe.proto.Campaign result) {
      if (targetBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          target_ = java.util.Collections.unmodifiableList(target_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
    }

    private void buildPartial0(com.hzs.SegServe.proto.Campaign result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.campaignId_ = campaignId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.campaignName_ = campaignName_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ruleId_ = ruleId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.schedule_ = scheduleBuilder_ == null
            ? schedule_
            : scheduleBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hzs.SegServe.proto.Campaign) {
        return mergeFrom((com.hzs.SegServe.proto.Campaign)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hzs.SegServe.proto.Campaign other) {
      if (other == com.hzs.SegServe.proto.Campaign.getDefaultInstance()) return this;
      if (other.hasCampaignId()) {
        campaignId_ = other.campaignId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCampaignName()) {
        campaignName_ = other.campaignName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasRuleId()) {
        ruleId_ = other.ruleId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasSchedule()) {
        mergeSchedule(other.getSchedule());
      }
      if (targetBuilder_ == null) {
        if (!other.target_.isEmpty()) {
          if (target_.isEmpty()) {
            target_ = other.target_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTargetIsMutable();
            target_.addAll(other.target_);
          }
          onChanged();
        }
      } else {
        if (!other.target_.isEmpty()) {
          if (targetBuilder_.isEmpty()) {
            targetBuilder_.dispose();
            targetBuilder_ = null;
            target_ = other.target_;
            bitField0_ = (bitField0_ & ~0x00000010);
            targetBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTargetFieldBuilder() : null;
          } else {
            targetBuilder_.addAllMessages(other.target_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              campaignId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              campaignName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ruleId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getScheduleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              com.hzs.SegServe.proto.Target m =
                  input.readMessage(
                      com.hzs.SegServe.proto.Target.parser(),
                      extensionRegistry);
              if (targetBuilder_ == null) {
                ensureTargetIsMutable();
                target_.add(m);
              } else {
                targetBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object campaignId_ = "";
    /**
     * <code>optional string campaign_id = 1;</code>
     * @return Whether the campaignId field is set.
     */
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string campaign_id = 1;</code>
     * @return The campaignId.
     */
    public java.lang.String getCampaignId() {
      java.lang.Object ref = campaignId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        campaignId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string campaign_id = 1;</code>
     * @return The bytes for campaignId.
     */
    public com.google.protobuf.ByteString
        getCampaignIdBytes() {
      java.lang.Object ref = campaignId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        campaignId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string campaign_id = 1;</code>
     * @param value The campaignId to set.
     * @return This builder for chaining.
     */
    public Builder setCampaignId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      campaignId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string campaign_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCampaignId() {
      campaignId_ = getDefaultInstance().getCampaignId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string campaign_id = 1;</code>
     * @param value The bytes for campaignId to set.
     * @return This builder for chaining.
     */
    public Builder setCampaignIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      campaignId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object campaignName_ = "";
    /**
     * <code>optional string campaign_name = 2;</code>
     * @return Whether the campaignName field is set.
     */
    public boolean hasCampaignName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string campaign_name = 2;</code>
     * @return The campaignName.
     */
    public java.lang.String getCampaignName() {
      java.lang.Object ref = campaignName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        campaignName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string campaign_name = 2;</code>
     * @return The bytes for campaignName.
     */
    public com.google.protobuf.ByteString
        getCampaignNameBytes() {
      java.lang.Object ref = campaignName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        campaignName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string campaign_name = 2;</code>
     * @param value The campaignName to set.
     * @return This builder for chaining.
     */
    public Builder setCampaignName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      campaignName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string campaign_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCampaignName() {
      campaignName_ = getDefaultInstance().getCampaignName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string campaign_name = 2;</code>
     * @param value The bytes for campaignName to set.
     * @return This builder for chaining.
     */
    public Builder setCampaignNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      campaignName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ruleId_ = "";
    /**
     * <code>optional string rule_id = 3;</code>
     * @return Whether the ruleId field is set.
     */
    public boolean hasRuleId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string rule_id = 3;</code>
     * @return The ruleId.
     */
    public java.lang.String getRuleId() {
      java.lang.Object ref = ruleId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string rule_id = 3;</code>
     * @return The bytes for ruleId.
     */
    public com.google.protobuf.ByteString
        getRuleIdBytes() {
      java.lang.Object ref = ruleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string rule_id = 3;</code>
     * @param value The ruleId to set.
     * @return This builder for chaining.
     */
    public Builder setRuleId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ruleId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string rule_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuleId() {
      ruleId_ = getDefaultInstance().getRuleId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string rule_id = 3;</code>
     * @param value The bytes for ruleId to set.
     * @return This builder for chaining.
     */
    public Builder setRuleIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ruleId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.hzs.SegServe.proto.Schedule schedule_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.Schedule, com.hzs.SegServe.proto.Schedule.Builder, com.hzs.SegServe.proto.ScheduleOrBuilder> scheduleBuilder_;
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     * @return Whether the schedule field is set.
     */
    public boolean hasSchedule() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     * @return The schedule.
     */
    public com.hzs.SegServe.proto.Schedule getSchedule() {
      if (scheduleBuilder_ == null) {
        return schedule_ == null ? com.hzs.SegServe.proto.Schedule.getDefaultInstance() : schedule_;
      } else {
        return scheduleBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public Builder setSchedule(com.hzs.SegServe.proto.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schedule_ = value;
      } else {
        scheduleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public Builder setSchedule(
        com.hzs.SegServe.proto.Schedule.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        schedule_ = builderForValue.build();
      } else {
        scheduleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public Builder mergeSchedule(com.hzs.SegServe.proto.Schedule value) {
      if (scheduleBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          schedule_ != null &&
          schedule_ != com.hzs.SegServe.proto.Schedule.getDefaultInstance()) {
          getScheduleBuilder().mergeFrom(value);
        } else {
          schedule_ = value;
        }
      } else {
        scheduleBuilder_.mergeFrom(value);
      }
      if (schedule_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public Builder clearSchedule() {
      bitField0_ = (bitField0_ & ~0x00000008);
      schedule_ = null;
      if (scheduleBuilder_ != null) {
        scheduleBuilder_.dispose();
        scheduleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public com.hzs.SegServe.proto.Schedule.Builder getScheduleBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getScheduleFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    public com.hzs.SegServe.proto.ScheduleOrBuilder getScheduleOrBuilder() {
      if (scheduleBuilder_ != null) {
        return scheduleBuilder_.getMessageOrBuilder();
      } else {
        return schedule_ == null ?
            com.hzs.SegServe.proto.Schedule.getDefaultInstance() : schedule_;
      }
    }
    /**
     * <code>optional .com.hzs.SegServe.proto.Schedule schedule = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hzs.SegServe.proto.Schedule, com.hzs.SegServe.proto.Schedule.Builder, com.hzs.SegServe.proto.ScheduleOrBuilder> 
        getScheduleFieldBuilder() {
      if (scheduleBuilder_ == null) {
        scheduleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hzs.SegServe.proto.Schedule, com.hzs.SegServe.proto.Schedule.Builder, com.hzs.SegServe.proto.ScheduleOrBuilder>(
                getSchedule(),
                getParentForChildren(),
                isClean());
        schedule_ = null;
      }
      return scheduleBuilder_;
    }

    private java.util.List<com.hzs.SegServe.proto.Target> target_ =
      java.util.Collections.emptyList();
    private void ensureTargetIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        target_ = new java.util.ArrayList<com.hzs.SegServe.proto.Target>(target_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hzs.SegServe.proto.Target, com.hzs.SegServe.proto.Target.Builder, com.hzs.SegServe.proto.TargetOrBuilder> targetBuilder_;

    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public java.util.List<com.hzs.SegServe.proto.Target> getTargetList() {
      if (targetBuilder_ == null) {
        return java.util.Collections.unmodifiableList(target_);
      } else {
        return targetBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public int getTargetCount() {
      if (targetBuilder_ == null) {
        return target_.size();
      } else {
        return targetBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public com.hzs.SegServe.proto.Target getTarget(int index) {
      if (targetBuilder_ == null) {
        return target_.get(index);
      } else {
        return targetBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder setTarget(
        int index, com.hzs.SegServe.proto.Target value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.set(index, value);
        onChanged();
      } else {
        targetBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder setTarget(
        int index, com.hzs.SegServe.proto.Target.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder addTarget(com.hzs.SegServe.proto.Target value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.add(value);
        onChanged();
      } else {
        targetBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder addTarget(
        int index, com.hzs.SegServe.proto.Target value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetIsMutable();
        target_.add(index, value);
        onChanged();
      } else {
        targetBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder addTarget(
        com.hzs.SegServe.proto.Target.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.add(builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder addTarget(
        int index, com.hzs.SegServe.proto.Target.Builder builderForValue) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder addAllTarget(
        java.lang.Iterable<? extends com.hzs.SegServe.proto.Target> values) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, target_);
        onChanged();
      } else {
        targetBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        targetBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public Builder removeTarget(int index) {
      if (targetBuilder_ == null) {
        ensureTargetIsMutable();
        target_.remove(index);
        onChanged();
      } else {
        targetBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public com.hzs.SegServe.proto.Target.Builder getTargetBuilder(
        int index) {
      return getTargetFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public com.hzs.SegServe.proto.TargetOrBuilder getTargetOrBuilder(
        int index) {
      if (targetBuilder_ == null) {
        return target_.get(index);  } else {
        return targetBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public java.util.List<? extends com.hzs.SegServe.proto.TargetOrBuilder> 
         getTargetOrBuilderList() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(target_);
      }
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public com.hzs.SegServe.proto.Target.Builder addTargetBuilder() {
      return getTargetFieldBuilder().addBuilder(
          com.hzs.SegServe.proto.Target.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public com.hzs.SegServe.proto.Target.Builder addTargetBuilder(
        int index) {
      return getTargetFieldBuilder().addBuilder(
          index, com.hzs.SegServe.proto.Target.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hzs.SegServe.proto.Target target = 5;</code>
     */
    public java.util.List<com.hzs.SegServe.proto.Target.Builder> 
         getTargetBuilderList() {
      return getTargetFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hzs.SegServe.proto.Target, com.hzs.SegServe.proto.Target.Builder, com.hzs.SegServe.proto.TargetOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hzs.SegServe.proto.Target, com.hzs.SegServe.proto.Target.Builder, com.hzs.SegServe.proto.TargetOrBuilder>(
                target_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hzs.SegServe.proto.Campaign)
  }

  // @@protoc_insertion_point(class_scope:com.hzs.SegServe.proto.Campaign)
  private static final com.hzs.SegServe.proto.Campaign DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hzs.SegServe.proto.Campaign();
  }

  public static com.hzs.SegServe.proto.Campaign getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Campaign>
      PARSER = new com.google.protobuf.AbstractParser<Campaign>() {
    @java.lang.Override
    public Campaign parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Campaign> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Campaign> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hzs.SegServe.proto.Campaign getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

