// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign.proto

package com.hzs.campaign_management_service.proto;

/**
 * <pre>
 * Represents a Play Activity Rule
 * </pre>
 *
 * Protobuf type {@code com.hzs.SegServe.proto.PlayActivityRule}
 */
public final class PlayActivityRule extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hzs.SegServe.proto.PlayActivityRule)
    PlayActivityRuleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PlayActivityRule.newBuilder() to construct.
  private PlayActivityRule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PlayActivityRule() {
    contentId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PlayActivityRule();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hzs.campaign_management_service.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_PlayActivityRule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hzs.campaign_management_service.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_PlayActivityRule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hzs.campaign_management_service.proto.PlayActivityRule.class, com.hzs.campaign_management_service.proto.PlayActivityRule.Builder.class);
  }

  private int bitField0_;
  public static final int CONTENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentId_ = "";
  /**
   * <code>optional string content_id = 1;</code>
   * @return Whether the contentId field is set.
   */
  @java.lang.Override
  public boolean hasContentId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string content_id = 1;</code>
   * @return The contentId.
   */
  @java.lang.Override
  public java.lang.String getContentId() {
    java.lang.Object ref = contentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string content_id = 1;</code>
   * @return The bytes for contentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentIdBytes() {
    java.lang.Object ref = contentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROGRESS_FIELD_NUMBER = 2;
  private long progress_ = 0L;
  /**
   * <code>optional int64 progress = 2;</code>
   * @return Whether the progress field is set.
   */
  @java.lang.Override
  public boolean hasProgress() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 progress = 2;</code>
   * @return The progress.
   */
  @java.lang.Override
  public long getProgress() {
    return progress_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, progress_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, progress_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hzs.campaign_management_service.proto.PlayActivityRule)) {
      return super.equals(obj);
    }
    com.hzs.campaign_management_service.proto.PlayActivityRule other = (com.hzs.campaign_management_service.proto.PlayActivityRule) obj;

    if (hasContentId() != other.hasContentId()) return false;
    if (hasContentId()) {
      if (!getContentId()
          .equals(other.getContentId())) return false;
    }
    if (hasProgress() != other.hasProgress()) return false;
    if (hasProgress()) {
      if (getProgress()
          != other.getProgress()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasContentId()) {
      hash = (37 * hash) + CONTENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getContentId().hashCode();
    }
    if (hasProgress()) {
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProgress());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.campaign_management_service.proto.PlayActivityRule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hzs.campaign_management_service.proto.PlayActivityRule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents a Play Activity Rule
   * </pre>
   *
   * Protobuf type {@code com.hzs.SegServe.proto.PlayActivityRule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hzs.SegServe.proto.PlayActivityRule)
      com.hzs.campaign_management_service.proto.PlayActivityRuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzs.campaign_management_service.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_PlayActivityRule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzs.campaign_management_service.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_PlayActivityRule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzs.campaign_management_service.proto.PlayActivityRule.class, com.hzs.campaign_management_service.proto.PlayActivityRule.Builder.class);
    }

    // Construct using com.hzs.SegServe.proto.PlayActivityRule.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      contentId_ = "";
      progress_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hzs.campaign_management_service.proto.CampaignProto.internal_static_com_hzs_SegServe_proto_PlayActivityRule_descriptor;
    }

    @java.lang.Override
    public com.hzs.campaign_management_service.proto.PlayActivityRule getDefaultInstanceForType() {
      return com.hzs.campaign_management_service.proto.PlayActivityRule.getDefaultInstance();
    }

    @java.lang.Override
    public com.hzs.campaign_management_service.proto.PlayActivityRule build() {
      com.hzs.campaign_management_service.proto.PlayActivityRule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hzs.campaign_management_service.proto.PlayActivityRule buildPartial() {
      com.hzs.campaign_management_service.proto.PlayActivityRule result = new com.hzs.campaign_management_service.proto.PlayActivityRule(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hzs.campaign_management_service.proto.PlayActivityRule result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.contentId_ = contentId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.progress_ = progress_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hzs.campaign_management_service.proto.PlayActivityRule) {
        return mergeFrom((com.hzs.campaign_management_service.proto.PlayActivityRule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hzs.campaign_management_service.proto.PlayActivityRule other) {
      if (other == com.hzs.campaign_management_service.proto.PlayActivityRule.getDefaultInstance()) return this;
      if (other.hasContentId()) {
        contentId_ = other.contentId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasProgress()) {
        setProgress(other.getProgress());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              contentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              progress_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object contentId_ = "";
    /**
     * <code>optional string content_id = 1;</code>
     * @return Whether the contentId field is set.
     */
    public boolean hasContentId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string content_id = 1;</code>
     * @return The contentId.
     */
    public java.lang.String getContentId() {
      java.lang.Object ref = contentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string content_id = 1;</code>
     * @return The bytes for contentId.
     */
    public com.google.protobuf.ByteString
        getContentIdBytes() {
      java.lang.Object ref = contentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string content_id = 1;</code>
     * @param value The contentId to set.
     * @return This builder for chaining.
     */
    public Builder setContentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string content_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentId() {
      contentId_ = getDefaultInstance().getContentId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string content_id = 1;</code>
     * @param value The bytes for contentId to set.
     * @return This builder for chaining.
     */
    public Builder setContentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long progress_ ;
    /**
     * <code>optional int64 progress = 2;</code>
     * @return Whether the progress field is set.
     */
    @java.lang.Override
    public boolean hasProgress() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 progress = 2;</code>
     * @return The progress.
     */
    @java.lang.Override
    public long getProgress() {
      return progress_;
    }
    /**
     * <code>optional int64 progress = 2;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(long value) {

      progress_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 progress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      bitField0_ = (bitField0_ & ~0x00000002);
      progress_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hzs.SegServe.proto.PlayActivityRule)
  }

  // @@protoc_insertion_point(class_scope:com.hzs.SegServe.proto.PlayActivityRule)
  private static final com.hzs.campaign_management_service.proto.PlayActivityRule DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hzs.campaign_management_service.proto.PlayActivityRule();
  }

  public static com.hzs.campaign_management_service.proto.PlayActivityRule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayActivityRule>
      PARSER = new com.google.protobuf.AbstractParser<PlayActivityRule>() {
    @java.lang.Override
    public PlayActivityRule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayActivityRule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayActivityRule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hzs.campaign_management_service.proto.PlayActivityRule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

