// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule_record.proto

package com.hzs.rule_status_monitor.proto;

/**
 * Protobuf type {@code com.hzs.rule_status_monitor.proto.RuleRecord}
 */
public final class RuleRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hzs.rule_status_monitor.proto.RuleRecord)
    RuleRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RuleRecord.newBuilder() to construct.
  private RuleRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RuleRecord() {
    id_ = "";
    ruleName_ = "";
    timestamp_ = "";
    status_ = 0;
    log_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RuleRecord();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hzs.rule_status_monitor.proto.RuleRecordProto.internal_static_com_hzs_rule_status_monitor_proto_RuleRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hzs.rule_status_monitor.proto.RuleRecordProto.internal_static_com_hzs_rule_status_monitor_proto_RuleRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hzs.rule_status_monitor.proto.RuleRecord.class, com.hzs.rule_status_monitor.proto.RuleRecord.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RULE_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ruleName_ = "";
  /**
   * <code>string rule_name = 2;</code>
   * @return The ruleName.
   */
  @java.lang.Override
  public java.lang.String getRuleName() {
    java.lang.Object ref = ruleName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ruleName_ = s;
      return s;
    }
  }
  /**
   * <code>string rule_name = 2;</code>
   * @return The bytes for ruleName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRuleNameBytes() {
    java.lang.Object ref = ruleName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ruleName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private long version_ = 0L;
  /**
   * <code>int64 version = 3;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestamp_ = "";
  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_ = 0;
  /**
   * <pre>
   * Use the Status enum for the status field
   * </pre>
   *
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Use the Status enum for the status field
   * </pre>
   *
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
   * @return The status.
   */
  @java.lang.Override public com.hzs.rule_status_monitor.proto.Status getStatus() {
    com.hzs.rule_status_monitor.proto.Status result = com.hzs.rule_status_monitor.proto.Status.forNumber(status_);
    return result == null ? com.hzs.rule_status_monitor.proto.Status.UNRECOGNIZED : result;
  }

  public static final int PROGRESS_FIELD_NUMBER = 6;
  private int progress_ = 0;
  /**
   * <pre>
   * Progress value between 1 and 100
   * </pre>
   *
   * <code>int32 progress = 6;</code>
   * @return The progress.
   */
  @java.lang.Override
  public int getProgress() {
    return progress_;
  }

  public static final int LOG_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair> log_;
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair> getLogList() {
    return log_;
  }
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder> 
      getLogOrBuilderList() {
    return log_;
  }
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  @java.lang.Override
  public int getLogCount() {
    return log_.size();
  }
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  @java.lang.Override
  public com.hzs.rule_status_monitor.proto.StatusTsPair getLog(int index) {
    return log_.get(index);
  }
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  @java.lang.Override
  public com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder getLogOrBuilder(
      int index) {
    return log_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ruleName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleName_);
    }
    if (version_ != 0L) {
      output.writeInt64(3, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timestamp_);
    }
    if (status_ != com.hzs.rule_status_monitor.proto.Status.UNKNOWN.getNumber()) {
      output.writeEnum(5, status_);
    }
    if (progress_ != 0) {
      output.writeInt32(6, progress_);
    }
    for (int i = 0; i < log_.size(); i++) {
      output.writeMessage(7, log_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ruleName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleName_);
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timestamp_);
    }
    if (status_ != com.hzs.rule_status_monitor.proto.Status.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, status_);
    }
    if (progress_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, progress_);
    }
    for (int i = 0; i < log_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, log_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hzs.rule_status_monitor.proto.RuleRecord)) {
      return super.equals(obj);
    }
    com.hzs.rule_status_monitor.proto.RuleRecord other = (com.hzs.rule_status_monitor.proto.RuleRecord) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getRuleName()
        .equals(other.getRuleName())) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (status_ != other.status_) return false;
    if (getProgress()
        != other.getProgress()) return false;
    if (!getLogList()
        .equals(other.getLogList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + RULE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getRuleName().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProgress();
    if (getLogCount() > 0) {
      hash = (37 * hash) + LOG_FIELD_NUMBER;
      hash = (53 * hash) + getLogList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hzs.rule_status_monitor.proto.RuleRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hzs.rule_status_monitor.proto.RuleRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hzs.rule_status_monitor.proto.RuleRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hzs.rule_status_monitor.proto.RuleRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hzs.rule_status_monitor.proto.RuleRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hzs.rule_status_monitor.proto.RuleRecord)
      com.hzs.rule_status_monitor.proto.RuleRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzs.rule_status_monitor.proto.RuleRecordProto.internal_static_com_hzs_rule_status_monitor_proto_RuleRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzs.rule_status_monitor.proto.RuleRecordProto.internal_static_com_hzs_rule_status_monitor_proto_RuleRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzs.rule_status_monitor.proto.RuleRecord.class, com.hzs.rule_status_monitor.proto.RuleRecord.Builder.class);
    }

    // Construct using com.hzs.rule_status_monitor.proto.RuleRecord.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      ruleName_ = "";
      version_ = 0L;
      timestamp_ = "";
      status_ = 0;
      progress_ = 0;
      if (logBuilder_ == null) {
        log_ = java.util.Collections.emptyList();
      } else {
        log_ = null;
        logBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hzs.rule_status_monitor.proto.RuleRecordProto.internal_static_com_hzs_rule_status_monitor_proto_RuleRecord_descriptor;
    }

    @java.lang.Override
    public com.hzs.rule_status_monitor.proto.RuleRecord getDefaultInstanceForType() {
      return com.hzs.rule_status_monitor.proto.RuleRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.hzs.rule_status_monitor.proto.RuleRecord build() {
      com.hzs.rule_status_monitor.proto.RuleRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hzs.rule_status_monitor.proto.RuleRecord buildPartial() {
      com.hzs.rule_status_monitor.proto.RuleRecord result = new com.hzs.rule_status_monitor.proto.RuleRecord(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.hzs.rule_status_monitor.proto.RuleRecord result) {
      if (logBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          log_ = java.util.Collections.unmodifiableList(log_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.log_ = log_;
      } else {
        result.log_ = logBuilder_.build();
      }
    }

    private void buildPartial0(com.hzs.rule_status_monitor.proto.RuleRecord result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ruleName_ = ruleName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.progress_ = progress_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hzs.rule_status_monitor.proto.RuleRecord) {
        return mergeFrom((com.hzs.rule_status_monitor.proto.RuleRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hzs.rule_status_monitor.proto.RuleRecord other) {
      if (other == com.hzs.rule_status_monitor.proto.RuleRecord.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRuleName().isEmpty()) {
        ruleName_ = other.ruleName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getProgress() != 0) {
        setProgress(other.getProgress());
      }
      if (logBuilder_ == null) {
        if (!other.log_.isEmpty()) {
          if (log_.isEmpty()) {
            log_ = other.log_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureLogIsMutable();
            log_.addAll(other.log_);
          }
          onChanged();
        }
      } else {
        if (!other.log_.isEmpty()) {
          if (logBuilder_.isEmpty()) {
            logBuilder_.dispose();
            logBuilder_ = null;
            log_ = other.log_;
            bitField0_ = (bitField0_ & ~0x00000040);
            logBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLogFieldBuilder() : null;
          } else {
            logBuilder_.addAllMessages(other.log_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ruleName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              version_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              timestamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              progress_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              com.hzs.rule_status_monitor.proto.StatusTsPair m =
                  input.readMessage(
                      com.hzs.rule_status_monitor.proto.StatusTsPair.parser(),
                      extensionRegistry);
              if (logBuilder_ == null) {
                ensureLogIsMutable();
                log_.add(m);
              } else {
                logBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object ruleName_ = "";
    /**
     * <code>string rule_name = 2;</code>
     * @return The ruleName.
     */
    public java.lang.String getRuleName() {
      java.lang.Object ref = ruleName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rule_name = 2;</code>
     * @return The bytes for ruleName.
     */
    public com.google.protobuf.ByteString
        getRuleNameBytes() {
      java.lang.Object ref = ruleName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rule_name = 2;</code>
     * @param value The ruleName to set.
     * @return This builder for chaining.
     */
    public Builder setRuleName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ruleName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string rule_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRuleName() {
      ruleName_ = getDefaultInstance().getRuleName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string rule_name = 2;</code>
     * @param value The bytes for ruleName to set.
     * @return This builder for chaining.
     */
    public Builder setRuleNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ruleName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 3;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {

      version_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      version_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 4;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 4;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 4;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Use the Status enum for the status field
     * </pre>
     *
     * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Use the Status enum for the status field
     * </pre>
     *
     * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Use the Status enum for the status field
     * </pre>
     *
     * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.hzs.rule_status_monitor.proto.Status getStatus() {
      com.hzs.rule_status_monitor.proto.Status result = com.hzs.rule_status_monitor.proto.Status.forNumber(status_);
      return result == null ? com.hzs.rule_status_monitor.proto.Status.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Use the Status enum for the status field
     * </pre>
     *
     * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.hzs.rule_status_monitor.proto.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Use the Status enum for the status field
     * </pre>
     *
     * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = 0;
      onChanged();
      return this;
    }

    private int progress_ ;
    /**
     * <pre>
     * Progress value between 1 and 100
     * </pre>
     *
     * <code>int32 progress = 6;</code>
     * @return The progress.
     */
    @java.lang.Override
    public int getProgress() {
      return progress_;
    }
    /**
     * <pre>
     * Progress value between 1 and 100
     * </pre>
     *
     * <code>int32 progress = 6;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(int value) {

      progress_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Progress value between 1 and 100
     * </pre>
     *
     * <code>int32 progress = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      bitField0_ = (bitField0_ & ~0x00000020);
      progress_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair> log_ =
      java.util.Collections.emptyList();
    private void ensureLogIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        log_ = new java.util.ArrayList<com.hzs.rule_status_monitor.proto.StatusTsPair>(log_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hzs.rule_status_monitor.proto.StatusTsPair, com.hzs.rule_status_monitor.proto.StatusTsPair.Builder, com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder> logBuilder_;

    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair> getLogList() {
      if (logBuilder_ == null) {
        return java.util.Collections.unmodifiableList(log_);
      } else {
        return logBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public int getLogCount() {
      if (logBuilder_ == null) {
        return log_.size();
      } else {
        return logBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public com.hzs.rule_status_monitor.proto.StatusTsPair getLog(int index) {
      if (logBuilder_ == null) {
        return log_.get(index);
      } else {
        return logBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder setLog(
        int index, com.hzs.rule_status_monitor.proto.StatusTsPair value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.set(index, value);
        onChanged();
      } else {
        logBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder setLog(
        int index, com.hzs.rule_status_monitor.proto.StatusTsPair.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.set(index, builderForValue.build());
        onChanged();
      } else {
        logBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder addLog(com.hzs.rule_status_monitor.proto.StatusTsPair value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.add(value);
        onChanged();
      } else {
        logBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder addLog(
        int index, com.hzs.rule_status_monitor.proto.StatusTsPair value) {
      if (logBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLogIsMutable();
        log_.add(index, value);
        onChanged();
      } else {
        logBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder addLog(
        com.hzs.rule_status_monitor.proto.StatusTsPair.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.add(builderForValue.build());
        onChanged();
      } else {
        logBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder addLog(
        int index, com.hzs.rule_status_monitor.proto.StatusTsPair.Builder builderForValue) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.add(index, builderForValue.build());
        onChanged();
      } else {
        logBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder addAllLog(
        java.lang.Iterable<? extends com.hzs.rule_status_monitor.proto.StatusTsPair> values) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, log_);
        onChanged();
      } else {
        logBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder clearLog() {
      if (logBuilder_ == null) {
        log_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        logBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public Builder removeLog(int index) {
      if (logBuilder_ == null) {
        ensureLogIsMutable();
        log_.remove(index);
        onChanged();
      } else {
        logBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public com.hzs.rule_status_monitor.proto.StatusTsPair.Builder getLogBuilder(
        int index) {
      return getLogFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder getLogOrBuilder(
        int index) {
      if (logBuilder_ == null) {
        return log_.get(index);  } else {
        return logBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public java.util.List<? extends com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder> 
         getLogOrBuilderList() {
      if (logBuilder_ != null) {
        return logBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(log_);
      }
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public com.hzs.rule_status_monitor.proto.StatusTsPair.Builder addLogBuilder() {
      return getLogFieldBuilder().addBuilder(
          com.hzs.rule_status_monitor.proto.StatusTsPair.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public com.hzs.rule_status_monitor.proto.StatusTsPair.Builder addLogBuilder(
        int index) {
      return getLogFieldBuilder().addBuilder(
          index, com.hzs.rule_status_monitor.proto.StatusTsPair.getDefaultInstance());
    }
    /**
     * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
     */
    public java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair.Builder> 
         getLogBuilderList() {
      return getLogFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hzs.rule_status_monitor.proto.StatusTsPair, com.hzs.rule_status_monitor.proto.StatusTsPair.Builder, com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder> 
        getLogFieldBuilder() {
      if (logBuilder_ == null) {
        logBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hzs.rule_status_monitor.proto.StatusTsPair, com.hzs.rule_status_monitor.proto.StatusTsPair.Builder, com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder>(
                log_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        log_ = null;
      }
      return logBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hzs.rule_status_monitor.proto.RuleRecord)
  }

  // @@protoc_insertion_point(class_scope:com.hzs.rule_status_monitor.proto.RuleRecord)
  private static final com.hzs.rule_status_monitor.proto.RuleRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hzs.rule_status_monitor.proto.RuleRecord();
  }

  public static com.hzs.rule_status_monitor.proto.RuleRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RuleRecord>
      PARSER = new com.google.protobuf.AbstractParser<RuleRecord>() {
    @java.lang.Override
    public RuleRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RuleRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RuleRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hzs.rule_status_monitor.proto.RuleRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

