// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule_record.proto

package com.hzs.rule_status_monitor.proto;

public interface RuleRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzs.rule_status_monitor.proto.RuleRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string rule_name = 2;</code>
   * @return The ruleName.
   */
  java.lang.String getRuleName();
  /**
   * <code>string rule_name = 2;</code>
   * @return The bytes for ruleName.
   */
  com.google.protobuf.ByteString
      getRuleNameBytes();

  /**
   * <code>int64 version = 3;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <pre>
   * Use the Status enum for the status field
   * </pre>
   *
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Use the Status enum for the status field
   * </pre>
   *
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 5;</code>
   * @return The status.
   */
  com.hzs.rule_status_monitor.proto.Status getStatus();

  /**
   * <pre>
   * Progress value between 1 and 100
   * </pre>
   *
   * <code>int32 progress = 6;</code>
   * @return The progress.
   */
  int getProgress();

  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  java.util.List<com.hzs.rule_status_monitor.proto.StatusTsPair> 
      getLogList();
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  com.hzs.rule_status_monitor.proto.StatusTsPair getLog(int index);
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  int getLogCount();
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  java.util.List<? extends com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder> 
      getLogOrBuilderList();
  /**
   * <code>repeated .com.hzs.rule_status_monitor.proto.StatusTsPair log = 7;</code>
   */
  com.hzs.rule_status_monitor.proto.StatusTsPairOrBuilder getLogOrBuilder(
      int index);
}
