// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule_record.proto

package com.hzs.rule_status_monitor.proto;

/**
 * Protobuf enum {@code com.hzs.rule_status_monitor.proto.Status}
 */
public enum Status
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>ACK = 1;</code>
   */
  ACK(1),
  /**
   * <code>ERROR = 2;</code>
   */
  ERROR(2),
  /**
   * <code>TIMEOUT = 3;</code>
   */
  TIMEOUT(3),
  /**
   * <code>COMPUTING = 4;</code>
   */
  COMPUTING(4),
  /**
   * <code>SUCCESS = 5;</code>
   */
  SUCCESS(5),
  /**
   * <code>FAN_OUT = 6;</code>
   */
  FAN_OUT(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>ACK = 1;</code>
   */
  public static final int ACK_VALUE = 1;
  /**
   * <code>ERROR = 2;</code>
   */
  public static final int ERROR_VALUE = 2;
  /**
   * <code>TIMEOUT = 3;</code>
   */
  public static final int TIMEOUT_VALUE = 3;
  /**
   * <code>COMPUTING = 4;</code>
   */
  public static final int COMPUTING_VALUE = 4;
  /**
   * <code>SUCCESS = 5;</code>
   */
  public static final int SUCCESS_VALUE = 5;
  /**
   * <code>FAN_OUT = 6;</code>
   */
  public static final int FAN_OUT_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Status forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return ACK;
      case 2: return ERROR;
      case 3: return TIMEOUT;
      case 4: return COMPUTING;
      case 5: return SUCCESS;
      case 6: return FAN_OUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hzs.rule_status_monitor.proto.RuleRecordProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Status[] VALUES = values();

  public static Status valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.hzs.rule_status_monitor.proto.Status)
}

