// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rule_record.proto

package com.hzs.rule_status_monitor.proto;

public interface StatusTsPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hzs.rule_status_monitor.proto.StatusTsPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.com.hzs.rule_status_monitor.proto.Status status = 1;</code>
   * @return The status.
   */
  com.hzs.rule_status_monitor.proto.Status getStatus();

  /**
   * <code>string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <pre>
   * Progress value between 1 and 100
   * </pre>
   *
   * <code>int32 progress = 3;</code>
   * @return The progress.
   */
  int getProgress();
}
